language: php
php:
  	- '5.6'
  
services:
  	- mysql

install: 
	- composer update
	
before_script:
  	- mysql -u root -e 'CREATE DATABASE php_project_1;'
 	- mysql -u root php_project_1 < database/php_project_1.sql
	
script: 
	- phpunit